site_name: 'bigbankloanaccelerator'
repo_url: https://github.com/surfers-lookout/bigbank-accelerator-creditcheck
repo_name: Github
edit_uri: blob/main/docs/
docs_dir: docs
nav:
  - Home: index.md
  - Tasks: tasks.md
  - Bugs: bugs.md
plugins:
  - techdocs-core
