
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bigbankloanaccelerator
  namespace: default
  description: Big Bank Credit Check Component
  tags:
    - app-accelerator
    - python
    - web
    - tanzu
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=bigbank'
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: group:banker-crew
  system: banker-system
  providesApis:
    - default/creditcheck-tap2.tanzu.rocks # need to replace with the correct context for the deployment
    # - <namespace>/<name>-<tap root dns> is the syntax
