apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: bigbankloanaccelerator
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: bigbank
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/language: python
    apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  params:
  - name: clusterBuilder
    value: full-jammy
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/language: python
  - name: annotations
    value:
      autoscaling.knative.dev/min-scale: "1"
      autoscaling.knative.dev/max-scale: "50"
      autoscaling.knative.dev/scale-down-delay: "2s"
      autoscaling.knative.dev/initial-scale: "1"
      autoscaling.knative.dev/window: "10s"
      autoscaling.knative.dev/target: "40"
      autoscaling.knative.dev/metric: "rps"
      autoscaling.knative.dev/target: "60"
  - name: api_descriptor
    value:
      type: openapi
      location:
        path: "/api/v1/api-docs"
      owner: group:banker-crew
      system: bigbank-system
      description: "Bigbank REST API accelerator"
  source:
    git:
      url: https://github.com/surfers-lookout/bigbank-accelerator-creditcheck
      ref:
        branch: main
